name: Deploy Backend Despachos

on:
  push:
    branches:
      - deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Login a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build y push imagen Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: nosecomo/back-despachos-innovatech:latest

      - name: Deploy en EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_BACKEND_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull nosecomo/back-despachos-innovatech:latest
            docker stop backend-despachos || true
            docker rm backend-despachos || true
            docker run -d \
              --name backend-despachos \
              -p 8081:8081 \
              -e DB_ENDPOINT=${{ secrets.DB_ENDPOINT }} \
              -e DB_PORT=3306 \
              -e DB_NAME=db_despachos \
              -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
              -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              nosecomo/back-despachos-innovatech:latest